### ISSUE TITLE
pricing information incorrect

### ISSUE THREAD

**Issue by DougAtIBM** [ibm-cloud-docs/CDN#28]
Hi, this is what it says in the FAQ regarding pricing:
**Where do I find cost estimates for CDN?**
_You can estimate the cost of a service using the cost estimator on the provisioning pages for CDN offerings. For example, log in to the [IBM Cloud Content Delivery Network](https://cloud.ibm.com/catalog/infrastructure/cdn-powered-by-akamai) console and click Create. As you complete the ordering form, cost estimates appear in the Summary side panel._

This is incorrect. No pricing is given anywhere in the UI, it looks like the cost calculator wasn't finished and instead it points back to theis FAQ page.

Please have this corrected.

**Comment by austinmama** [comment]
@sheltons Please investigate

**Comment by sheltons** [comment]
Created an issue in the staging repo, and asked for developer assistance on the cost calculator. Will update as I learn more.

**Comment by sheltons** [comment]
Content updated in staging and production. Pricing instructions have been corrected.
